export const GET_LIST = 'GET_LIST'
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS'
export const GET_LIST_ERROR = 'GET_LIST_ERROR'

export const GET_DETAIL = 'GET_DETAIL'
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS'
export const GET_DETAIL_ERROR = 'GET_DETAIL_ERROR'

export const IS_FETCHING_PRODUCT = 'IS_FETCHING_PRODUCT'
